---

version: '3.7'

services:

    backend:
        container_name: onacut_back
        build: ./backend
        ports:
          - 5000:5000
        stdin_open: true 

    frontend:
        container_name: onacut_front
        build: ./frontend
        ports:
          - 3000:80
        stdin_open: true 
        depends_on:
            - backend
